# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: "sesam"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: "checksums.txt"

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/app
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
