# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: "sesam"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: "checksums.txt"

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/app
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    annotations:
      "org.opencontainers.image.version":  "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.source":   "{{ .GitURL }}"
      "org.opencontainers.image.created":  "{{ .Date }}"
    disable: "{{ .IsSnapshot }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
